name: deploy subgraph
description: deploy subgraph to subgraph hosting service
inputs:
  deploy_key:
    description: "Your deploy key for the subgraph studio"
    required: true
  version_label:
    description: "Your version label for subgraph studio"
    required: true
  subgraph_name:
    description: "The name of the subgraph"
    required: true
  network:
    description: "Select the network in network config file"
    required: false
  network-file:
    description: "Select the network file path"
    required: false
    default: "networks.yml"
  node:
    description: "Select the network in network config file"
    required: false
    default: "https://api.studio.thegraph.com/deploy/"
  ipfs:
    description: "Select the network in network config file"
    required: false
    default: "https://api.thegraph.com/ipfs/api/v0"
  config_file:
    description: "The config file you will use to deploy"
    required: false
    default: "subgraph.yml"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: "9.13.2"
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: setup graph
      shell: bash
      run: |
        pnpm install --frozen-lockfile
        pnpm run codegen \
          ${{inputs.config_file}}
        pnpm run build \
          ${{inputs.config_file}}
        pnpm run publish:thegraph \
          ${{inputs.subgraph_name}} \
          ${{inputs.config_file}} \
          --version-label ${{ inputs.version_label }} \
          --deploy-key ${{ inputs.deploy_key }} \
          --network ${{ inputs.network }} \
          --node ${{ inputs.node }} \
          --ipfs ${{ inputs.ipfs }}
